package com.online.plant.constants;

public interface UIConstants {

    String APPLICATION_TITLE = "Online Plant";

    String HTML_END = "</body>\n"
            + "</html>";

    String HTML_START = "<!DOCTYPE html>\n"
            + "<html lang=\"en\">\n"
            + "<head>";

    String ELEMENT_HEADER = "<meta charset=\"utf-8\">\n"
            + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
            + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
            + "    <meta name=\"description\" content=\"\">\n"
            + "    <meta name=\"author\" content=\"\">\n"
            + "    <title>" + APPLICATION_TITLE + "</title>\n"
            + "    <link href=\"/assets/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n"
            + "    <link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\n"
            + "    <link href=\"/assets/css/sb-admin-2.min.css\" rel=\"stylesheet\">"
            + "    <link href=\"/assets/vendor/datatables/dataTables.bootstrap4.min.css\" rel=\"stylesheet\">";

    String BODY_START = "</head>"
            + "<body id=\"page-top\">\n"
            + "    <div id=\"wrapper\">\n"
            + "        <div id=\"content-wrapper\" class=\"d-flex flex-column\">\n"
            + "            <div id=\"content\">";

    String BODY_END = "</div>\n"
            + "    </div>\n"
            + "    <a class=\"scroll-to-top rounded\" href=\"#page-top\">\n"
            + "        <i class=\"fas fa-angle-up\"></i>\n"
            + "    </a>";

    String CONTENT_INDEX_FORMATTED = "<div class=\"container-fluid\">\n"
            + "                    <div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\n"
            + "                        <h1 class=\"h3 mb-0 text-gray-800\">Home</h1>\n"
            + "                        <a href=\"%s\" class=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\">\n"
            + "						<i class=\"fas fa-download fa-sm text-white-50\"></i>List Transactions</a>\n"
            + "                    </div>\n"
            + "                    <div class=\"row\">\n"
            + "                        <div class=\"col-lg-12 mb-4\">\n"
            + "                            <div class=\"card shadow mb-4\">\n"
            + "                                <div class=\"card-header py-3\">\n"
            + "                                    <h6 class=\"m-0 font-weight-bold text-primary\">Welcome</h6>\n"
            + "                                </div>\n"
            + "                                <div class=\"card-body\">\n"
            + "                                    <div class=\"text-center\">\n"
            + "                                        <img class=\"img-fluid px-3 px-sm-4 mt-3 mb-4\" style=\"width: 25rem;\"\n"
            + "                                            src=\"/assets/img/undraw_posting_photo.svg\" alt=\"...\">\n"
            + "                                    </div>\n"
            + "                                    <p>Welcome in Online Plant </p>\n"
            + "                                    Click here to <a href=\"%s\">List Transactions &rarr;</a>\n"
            + "                                </div>\n"
            + "                            </div>\n"
            + "                        </div>\n"
            + "                    </div>\n"
            + "                </div>";

    String CONTENT_INDEX = "<div class=\"container-fluid\">\n"
            + "                    <div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\n"
            + "                        <h1 class=\"h3 mb-0 text-gray-800\">Home</h1>\n"
            + "                        <a href=\"#\" class=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\">\n"
            + "						<i class=\"fas fa-download fa-sm text-white-50\"></i> Generate Report</a>\n"
            + "                    </div>\n"
            + "                    <div class=\"row\">\n"
            + "                        <div class=\"col-lg-12 mb-4\">\n"
            + "                            <div class=\"card shadow mb-4\">\n"
            + "                                <div class=\"card-header py-3\">\n"
            + "                                    <h6 class=\"m-0 font-weight-bold text-primary\">Welcome</h6>\n"
            + "                                </div>\n"
            + "                                <div class=\"card-body\">\n"
            + "                                    <div class=\"text-center\">\n"
            + "                                        <img class=\"img-fluid px-3 px-sm-4 mt-3 mb-4\" style=\"width: 25rem;\"\n"
            + "                                            src=\"/assets/img/undraw_posting_photo.svg\" alt=\"...\">\n"
            + "                                    </div>\n"
            + "                                    <p>Add some quality, svg illustrations to your project courtesy of <a\n"
            + "                                            target=\"_blank\" rel=\"nofollow\" href=\"https://undraw.co/\">unDraw</a>, a\n"
            + "                                        constantly updated collection of beautiful svg images that you can use\n"
            + "                                        completely free and without attribution!</p>\n"
            + "                                    <a target=\"_blank\" rel=\"nofollow\" href=\"https://undraw.co/\">Browse Illustrations on\n"
            + "                                        unDraw &rarr;</a>\n"
            + "                                </div>\n"
            + "                            </div>\n"
            + "                        </div>\n"
            + "                    </div>\n"
            + "                </div>";

    String ELEMENT_FOOTER = "<footer class=\"sticky-footer bg-white\">\n"
            + "                <div class=\"container my-auto\">\n"
            + "                    <div class=\"copyright text-center my-auto\">\n"
            + "                        <span>Copyright &copy; " + APPLICATION_TITLE + " 2023</span>\n"
            + "                    </div>\n"
            + "                </div>\n"
            + "            </footer>";

    String ELEMENT_TOP_BAR = "<nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\n"
            + " <!-- Topbar Search -->\n"
            + "                    <form\n"
            + "                        class=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\n"
            + "                        <div class=\"input-group\">\n"
            + "                            <a href=\"%s\" class=\"d-none d-sm-inline-block btn btn-sm btn-success shadow-sm\"><i\n"
            + "                                class=\"fas fa-home fa-sm text-white-50\"></i>&ensp;Home</a>\n"
            + "                        </div>\n"
            + "                    </form>"
            + "                    <ul class=\"navbar-nav ml-auto\">\n"
            + "                        <div class=\"topbar-divider d-none d-sm-block\"></div>\n"
            + "                        <li class=\"nav-item dropdown no-arrow\">\n"
            + "                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\"\n"
            + "                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n"
            + "                                <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">%s</span>\n"
            + "                                <img class=\"img-profile rounded-circle\"\n"
            + "                                    src=\"/assets/img/undraw_profile.svg\">\n"
            + "                            </a>\n"
            + "                            <div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\n"
            + "                                aria-labelledby=\"userDropdown\">\n"
            + "                                <a class=\"dropdown-item\" href=\"logout\"\n"
            + "                                    <i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\n"
            + "                                    Logout\n"
            + "                                </a>\n"
            + "                            </div>\n"
            + "                        </li>\n"
            + "                    </ul>\n"
            + "                </nav>";

    String ELEMENT_TOP_BAR1 = "<nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\n"
            + "                    <button id=\"sidebarToggleTop\" class=\"btn btn-link d-md-none rounded-circle mr-3\">\n"
            + "                        <i class=\"fa fa-bars\"></i>\n"
            + "                    </button>\n"
            + "                    <form\n"
            + "                        class=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\n"
            + "                        <div class=\"input-group\">\n"
            + "                            <input type=\"text\" class=\"form-control bg-light border-0 small\" placeholder=\"Search for...\"\n"
            + "                                aria-label=\"Search\" aria-describedby=\"basic-addon2\">\n"
            + "                            <div class=\"input-group-append\">\n"
            + "                                <button class=\"btn btn-primary\" type=\"button\">\n"
            + "                                    <i class=\"fas fa-search fa-sm\"></i>\n"
            + "                                </button>\n"
            + "                            </div>\n"
            + "                        </div>\n"
            + "                    </form>\n"
            + "                    <ul class=\"navbar-nav ml-auto\">\n"
            + "                        <li class=\"nav-item dropdown no-arrow d-sm-none\">\n"
            + "                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"searchDropdown\" role=\"button\"\n"
            + "                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n"
            + "                                <i class=\"fas fa-search fa-fw\"></i>\n"
            + "                            </a>\n"
            + "                            <div class=\"dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in\"\n"
            + "                                aria-labelledby=\"searchDropdown\">\n"
            + "                                <form class=\"form-inline mr-auto w-100 navbar-search\">\n"
            + "                                    <div class=\"input-group\">\n"
            + "                                        <input type=\"text\" class=\"form-control bg-light border-0 small\"\n"
            + "                                            placeholder=\"Search for...\" aria-label=\"Search\"\n"
            + "                                            aria-describedby=\"basic-addon2\">\n"
            + "                                        <div class=\"input-group-append\">\n"
            + "                                            <button class=\"btn btn-primary\" type=\"button\">\n"
            + "                                                <i class=\"fas fa-search fa-sm\"></i>\n"
            + "                                            </button>\n"
            + "                                        </div>\n"
            + "                                    </div>\n"
            + "                                </form>\n"
            + "                            </div>\n"
            + "                        </li>\n"
            + "                        <li class=\"nav-item dropdown no-arrow mx-1\">\n"
            + "                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\" role=\"button\"\n"
            + "                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n"
            + "                                <i class=\"fas fa-bell fa-fw\"></i>\n"
            + "                                <!-- Counter - Alerts -->\n"
            + "                                <span class=\"badge badge-danger badge-counter\">3+</span>\n"
            + "                            </a>\n"
            + "                            <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\n"
            + "                                aria-labelledby=\"alertsDropdown\">\n"
            + "                                <h6 class=\"dropdown-header\">\n"
            + "                                    Alerts Center\n"
            + "                                </h6>\n"
            + "                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n"
            + "                                    <div class=\"mr-3\">\n"
            + "                                        <div class=\"icon-circle bg-primary\">\n"
            + "                                            <i class=\"fas fa-file-alt text-white\"></i>\n"
            + "                                        </div>\n"
            + "                                    </div>\n"
            + "                                    <div>\n"
            + "                                        <div class=\"small text-gray-500\">December 12, 2019</div>\n"
            + "                                        <span class=\"font-weight-bold\">A new monthly report is ready to download!</span>\n"
            + "                                    </div>\n"
            + "                                </a>\n"
            + "                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n"
            + "                                    <div class=\"mr-3\">\n"
            + "                                        <div class=\"icon-circle bg-success\">\n"
            + "                                            <i class=\"fas fa-donate text-white\"></i>\n"
            + "                                        </div>\n"
            + "                                    </div>\n"
            + "                                    <div>\n"
            + "                                        <div class=\"small text-gray-500\">December 7, 2019</div>\n"
            + "                                        $290.29 has been deposited into your account!\n"
            + "                                    </div>\n"
            + "                                </a>\n"
            + "                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n"
            + "                                    <div class=\"mr-3\">\n"
            + "                                        <div class=\"icon-circle bg-warning\">\n"
            + "                                            <i class=\"fas fa-exclamation-triangle text-white\"></i>\n"
            + "                                        </div>\n"
            + "                                    </div>\n"
            + "                                    <div>\n"
            + "                                        <div class=\"small text-gray-500\">December 2, 2019</div>\n"
            + "                                        Spending Alert: We've noticed unusually high spending for your account.\n"
            + "                                    </div>\n"
            + "                                </a>\n"
            + "                                <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Show All Alerts</a>\n"
            + "                            </div>\n"
            + "                        </li>\n"
            + "                        <li class=\"nav-item dropdown no-arrow mx-1\">\n"
            + "                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\" role=\"button\"\n"
            + "                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n"
            + "                                <i class=\"fas fa-envelope fa-fw\"></i>\n"
            + "                                <!-- Counter - Messages -->\n"
            + "                                <span class=\"badge badge-danger badge-counter\">7</span>\n"
            + "                            </a>\n"
            + "                            <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\n"
            + "                                aria-labelledby=\"messagesDropdown\">\n"
            + "                                <h6 class=\"dropdown-header\">\n"
            + "                                    Message Center\n"
            + "                                </h6>\n"
            + "                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n"
            + "                                    <div class=\"dropdown-list-image mr-3\">\n"
            + "                                        <img class=\"rounded-circle\" src=\"img/undraw_profile_1.svg\"\n"
            + "                                            alt=\"...\">\n"
            + "                                        <div class=\"status-indicator bg-success\"></div>\n"
            + "                                    </div>\n"
            + "                                    <div class=\"font-weight-bold\">\n"
            + "                                        <div class=\"text-truncate\">Hi there! I am wondering if you can help me with a\n"
            + "                                            problem I've been having.</div>\n"
            + "                                        <div class=\"small text-gray-500\">Emily Fowler · 58m</div>\n"
            + "                                    </div>\n"
            + "                                </a>\n"
            + "                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n"
            + "                                    <div class=\"dropdown-list-image mr-3\">\n"
            + "                                        <img class=\"rounded-circle\" src=\"img/undraw_profile_2.svg\"\n"
            + "                                            alt=\"...\">\n"
            + "                                        <div class=\"status-indicator\"></div>\n"
            + "                                    </div>\n"
            + "                                    <div>\n"
            + "                                        <div class=\"text-truncate\">I have the photos that you ordered last month, how\n"
            + "                                            would you like them sent to you?</div>\n"
            + "                                        <div class=\"small text-gray-500\">Jae Chun · 1d</div>\n"
            + "                                    </div>\n"
            + "                                </a>\n"
            + "                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n"
            + "                                    <div class=\"dropdown-list-image mr-3\">\n"
            + "                                        <img class=\"rounded-circle\" src=\"img/undraw_profile_3.svg\"\n"
            + "                                            alt=\"...\">\n"
            + "                                        <div class=\"status-indicator bg-warning\"></div>\n"
            + "                                    </div>\n"
            + "                                    <div>\n"
            + "                                        <div class=\"text-truncate\">Last month's report looks great, I am very happy with\n"
            + "                                            the progress so far, keep up the good work!</div>\n"
            + "                                        <div class=\"small text-gray-500\">Morgan Alvarez · 2d</div>\n"
            + "                                    </div>\n"
            + "                                </a>\n"
            + "                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n"
            + "                                    <div class=\"dropdown-list-image mr-3\">\n"
            + "                                        <img class=\"rounded-circle\" src=\"https://source.unsplash.com/Mv9hjnEUHR4/60x60\"\n"
            + "                                            alt=\"...\">\n"
            + "                                        <div class=\"status-indicator bg-success\"></div>\n"
            + "                                    </div>\n"
            + "                                    <div>\n"
            + "                                        <div class=\"text-truncate\">Am I a good boy? The reason I ask is because someone\n"
            + "                                            told me that people say this to all dogs, even if they aren't good...</div>\n"
            + "                                        <div class=\"small text-gray-500\">Chicken the Dog · 2w</div>\n"
            + "                                    </div>\n"
            + "                                </a>\n"
            + "                                <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Read More Messages</a>\n"
            + "                            </div>\n"
            + "                        </li>\n"
            + "                        <div class=\"topbar-divider d-none d-sm-block\"></div>\n"
            + "                        <li class=\"nav-item dropdown no-arrow\">\n"
            + "                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\"\n"
            + "                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n"
            + "                                <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">Douglas McGee</span>\n"
            + "                                <img class=\"img-profile rounded-circle\"\n"
            + "                                    src=\"img/undraw_profile.svg\">\n"
            + "                            </a>\n"
            + "                            <div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\n"
            + "                                aria-labelledby=\"userDropdown\">\n"
            + "                                <a class=\"dropdown-item\" href=\"#\">\n"
            + "                                    <i class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i>\n"
            + "                                    Profile\n"
            + "                                </a>\n"
            + "                                <a class=\"dropdown-item\" href=\"#\">\n"
            + "                                    <i class=\"fas fa-cogs fa-sm fa-fw mr-2 text-gray-400\"></i>\n"
            + "                                    Settings\n"
            + "                                </a>\n"
            + "                                <a class=\"dropdown-item\" href=\"#\">\n"
            + "                                    <i class=\"fas fa-list fa-sm fa-fw mr-2 text-gray-400\"></i>\n"
            + "                                    Activity Log\n"
            + "                                </a>\n"
            + "                                <div class=\"dropdown-divider\"></div>\n"
            + "                                <a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\" data-target=\"#logoutModal\">\n"
            + "                                    <i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\n"
            + "                                    Logout\n"
            + "                                </a>\n"
            + "                            </div>\n"
            + "                        </li>\n"
            + "                    </ul>\n"
            + "                </nav>";

    String ELEMENT_JAVASCRIPT = "<script src=\"/assets/vendor/jquery/jquery.min.js\"></script>\n"
            + "    <script src=\"/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n"
            + "    <script src=\"/assets/vendor/jquery-easing/jquery.easing.min.js\"></script>\n"
            + "    <script src=\"/assets/vendor/datatables/dataTables.bootstrap4.min.js\"></script>\n"
            + "    <script src=\"/assets/js/demo/datatables-demo.js\"></script>\n"
            + "    <script src=\"/assets/js/sb-admin-2.min.js\"></script>";

    String CONTENT_TRANSACTIONS_TABLE = "<div class=\"container-fluid\">\n"
            + "                    <h1 class=\"h3 mb-2 text-gray-800\">%s</h1>\n"
            + "                    <div class=\"card shadow mb-4\">\n"
            + "                        <div class=\"card-header py-3\">\n"
            + "                            <h6 class=\"m-0 font-weight-bold text-primary\">%s</h6>\n"
            + "                        </div>\n"
            + "                        <div class=\"card-body\">\n"
            + "                            <div class=\"table-responsive\">\n"
            + "                                <table class=\"table table-bordered\" id=\"dataTable\" width=\"100&percnt;\" cellspacing=\"0\">\n"
            + "                                    <thead>\n"
            + "                                        <tr>\n"
            + "                                            <th>Id</th>\n"
            + "                                            <th>Client</th>\n"
            + "                                            <th>Transaction</th>\n"
            + "                                            <th>Date</th>\n"
            + "                                            <th colspan=\"2\">Actions</th>\n"
            + "                                        </tr>\n"
            + "                                    </thead>\n"
            + "                                    <tbody>%s</tbody>\n"
            + "                                </table>\n"
            + "                            </div>\n"
            + "                        </div>\n"
            + "                    </div>\n"
            + "                </div>";

    String CONTENT_PRODUCTS_TABLE = "<div class=\"container-fluid\">\n"
            + "                    <h1 class=\"h3 mb-2 text-gray-800\">%s</h1>\n"
            + "                    <div class=\"card shadow mb-4\">\n"
            + "                        <div class=\"card-header py-3\">\n"
            + "                            <h6 class=\"m-0 font-weight-bold text-primary\">%s</h6>\n"
            + "                        </div>\n"
            + "                        <div class=\"card-body\">\n"
            + "                            <div class=\"table-responsive\">\n"
            + "                                <table class=\"table table-bordered\" id=\"dataTable\" width=\"100&percnt;\" cellspacing=\"0\">\n"
            + "                                    <thead>\n"
            + "                                        <tr>\n"
            + "                                            <th>Id</th>\n"
            + "                                            <th>Client</th>\n"
            + "                                            <th>Product</th>\n"
            + "                                            <th>Quantity</th>\n"
            + "                                            <th>Status</th>\n"
            + "                                            <th>Transaction</th>\n"
            + "                                            <th>Branch</th>\n"
            + "                                            <th>Date</th>\n"
            + "                                            <th colspan=\"2\">Actions</th>\n"
            + "                                        </tr>\n"
            + "                                    </thead>\n"
            + "                                    <tbody>%s</tbody>\n"
            + "                                </table>\n"
            + "                            </div>\n"
            + "                        </div>\n"
            + "                    </div>\n"
            + "                </div>";

    String CONTENT_TRANSACTIONS_DETAILS = "<div class=\"container-fluid\">\n"
            + "            <div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\n"
            + "                <h1 class=\"h3 mb-0 text-gray-800\">Home</h1>\n"
            + "            </div>\n"
            + "            <div class=\"row\">\n"
            + "                <div class=\"col-lg-12 mb-4\">\n"
            + "\n"
            + "                    <!-- Illustrations -->\n"
            + "                    <div class=\"card shadow mb-4\">\n"
            + "                        <div class=\"card-header py-3\">\n"
            + "                            <h6 class=\"m-0 font-weight-bold text-primary\">Your Transaction No is: %s</h6>\n"
            + "                        </div>\n"
            + "                        <div class=\"card-body\">\n"
            + "                            <div class=\"text-center\">\n"
            + "                                <div class=\"form-group\">\n"
            + "                                    <label>Transaction By</label>\n"
            + "                                    <input type=\"text\" readonly class=\"form-control\" value=\"%s\">\n"
            + "                                </div>\n"
            + "                                <div class=\"form-group\">\n"
            + "                                    <label>Transaction</label>\n"
            + "                                    <input type=\"text\" readonly class=\"form-control\" value=\"%s\">\n"
            + "                                </div>\n"
            + "                                \n"
            + "                                <a href=\"%s\" class=\"btn btn-primary\">View Products</a>\n"
            + "                                <a href=\"%s\" class=\"btn btn-info\">Add Products</a>\n"
            + "                                Click here to <a href=\"%s\">home &rarr;</a>\n"
            + "                            </div>\n"
            + "                        </div>\n"
            + "                    </div>\n"
            + "                </div>\n"
            + "            </div>";
}
